word_list=[
    "navgurukul",
    "family",
    "relationship",
    "maharashtra",
    "sapna",
    "environment",
    "human",
    "education",
    "nature",
    "teacher",
    "love",
    "friendm"]